services:
  - type: web
    name: depoimentos
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_PASSWORD
        generateValue: false
      - key: BASE_URL
        value: https://depoimentos.onrender.com
